<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR5XznYt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR5XznYt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR5XznYt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR5XznYt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR5XznYt\App_KernelDevDebugContainer([
    'container.build_hash' => 'R5XznYt',
    'container.build_id' => '3ac36926',
    'container.build_time' => 1650015247,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR5XznYt');
